version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mynotes.api:
    env_file:
     - .env
    build:
      context: ./MyNotes.Server
      dockerfile: Dockerfile
    container_name: mynotes_api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:${API_PORT}
      ConnectionStrings__DbConnection: ${MONGO_CONNECTION_STRING}
      ConnectionStrings__DatabaseName: ${MONGO_DB_NAME}
    ports:
      - "${API_PORT}:8083"
    depends_on:
      - mongo
    restart: always

  mynotes.ui:
    build:
      context: ./mynotes.client
      dockerfile: Dockerfile
    container_name: mynotes_ui
    ports:
      - "${UI_PORT}:80"
    depends_on:
      - mynotes.api
    restart: always

volumes:
  mongo_data:
